/**
 * Static Demo Jobs Collection
 * Preserves the curated showcase roles across Engineering, Design, Finance,
 * Marketing, Healthcare, Security, Education, and Engineering Ops.
 */

export const STATIC_DEMO_JOBS = [
  // Engineering
  {
    _id: "demo_1",
    id: "demo_1",
    category: "Engineering",
    title: "Senior Frontend Engineer",
    company: { name: "Vercel", location: "Remote" },
    companyName: "Vercel",
    location: "Remote",
    isRemote: true,
    jobType: "Full-time",
    type: "Full-time",
    salary: "₹24L – ₹36L / yr",
    salaryDisplay: "₹24L – ₹36L / yr",
    salaryMin: 2400000,
    salaryMax: 3600000,
    salaryCurrency: "INR",
    posted: "2h ago",
    postedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    logo: "VR",
    logoColor: "#fff",
    logoBg: "#000",
    tags: ["React", "TypeScript", "Next.js"],
    requirements: ["React", "TypeScript", "Next.js"],
    skills: ["React", "TypeScript", "Next.js"],
    description: "Build the next generation of web deployment infrastructure and high-performance React frameworks at Vercel. Collaborate across frontend platform teams to engineer lightning-fast developer experiences.",
    featured: true,
    isExternal: false,
    isDemo: true,
    provider: "demo",
    source: "demo",
  },
  {
    _id: "demo_4",
    id: "demo_4",
    category: "Engineering",
    title: "DevOps Engineer",
    company: { name: "PlanetScale", location: "Remote" },
    companyName: "PlanetScale",
    location: "Remote",
    isRemote: true,
    jobType: "Full-time",
    type: "Full-time",
    salary: "₹20L – ₹32L / yr",
    salaryDisplay: "₹20L – ₹32L / yr",
    salaryMin: 2000000,
    salaryMax: 3200000,
    salaryCurrency: "INR",
    posted: "2d ago",
    postedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    logo: "PS",
    logoColor: "#fff",
    logoBg: "#f97316",
    tags: ["Kubernetes", "AWS", "Terraform"],
    requirements: ["Kubernetes", "AWS", "Terraform"],
    skills: ["Kubernetes", "AWS", "Terraform"],
    description: "Manage and optimize mission-critical cloud infrastructure, automated CI/CD pipelines, and multi-region Kubernetes clusters for PlanetScale's serverless database platform.",
    featured: false,
    isExternal: false,
    isDemo: true,
    provider: "demo",
    source: "demo",
  },
  {
    _id: "demo_5",
    id: "demo_5",
    category: "Engineering",
    title: "Backend Engineer (Go)",
    company: { name: "Supabase", location: "Remote" },
    companyName: "Supabase",
    location: "Remote",
    isRemote: true,
    jobType: "Full-time",
    type: "Full-time",
    salary: "₹18L – ₹30L / yr",
    salaryDisplay: "₹18L – ₹30L / yr",
    salaryMin: 1800000,
    salaryMax: 3000000,
    salaryCurrency: "INR",
    posted: "3d ago",
    postedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    logo: "SB",
    logoColor: "#fff",
    logoBg: "#3ecf8e",
    tags: ["Go", "PostgreSQL", "Docker"],
    requirements: ["Go", "PostgreSQL", "Docker"],
    skills: ["Go", "PostgreSQL", "Docker"],
    description: "Architect open source developer tools, real-time database streaming, and distributed Go microservices that power thousands of backend applications worldwide.",
    featured: false,
    isExternal: false,
    isDemo: true,
    provider: "demo",
    source: "demo",
  },
  {
    _id: "demo_21",
    id: "demo_21",
    category: "Engineering",
    title: "iOS Engineer",
    company: { name: "Airbnb", location: "San Francisco, CA" },
    companyName: "Airbnb",
    location: "San Francisco, CA",
    isRemote: false,
    jobType: "Hybrid",
    type: "Hybrid",
    salary: "₹22L – ₹35L / yr",
    salaryDisplay: "₹22L – ₹35L / yr",
    salaryMin: 2200000,
    salaryMax: 3500000,
    salaryCurrency: "INR",
    posted: "1d ago",
    postedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    logo: "AB",
    logoColor: "#fff",
    logoBg: "#FF5A5F",
    tags: ["Swift", "UIKit", "Combine"],
    requirements: ["Swift", "UIKit", "Combine"],
    skills: ["Swift", "UIKit", "Combine"],
    description: "Create memorable mobile travel experiences for hundreds of millions of travelers. Implement robust animations, offline-first mobile architecture, and high-performance Swift code.",
    featured: false,
    isExternal: false,
    isDemo: true,
    provider: "demo",
    source: "demo",
  },
  // Design
  {
    _id: "demo_2",
    id: "demo_2",
    category: "Design",
    title: "Product Designer",
    company: { name: "Linear", location: "San Francisco, CA" },
    companyName: "Linear",
    location: "San Francisco, CA",
    isRemote: false,
    jobType: "Full-time",
    type: "Full-time",
    salary: "₹16L – ₹28L / yr",
    salaryDisplay: "₹16L – ₹28L / yr",
    salaryMin: 1600000,
    salaryMax: 2800000,
    salaryCurrency: "INR",
    posted: "5h ago",
    postedAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    logo: "LN",
    logoColor: "#fff",
    logoBg: "#5b6af7",
    tags: ["Figma", "Systems Design", "Motion"],
    requirements: ["Figma", "Systems Design", "Motion"],
    skills: ["Figma", "Systems Design", "Motion"],
    description: "Craft immaculate software interactions, keyboard-first workflows, and high-fidelity design systems for the tool of choice among modern engineering teams.",
    featured: false,
    isExternal: false,
    isDemo: true,
    provider: "demo",
    source: "demo",
  },
  {
    _id: "demo_7",
    id: "demo_7",
    category: "Design",
    title: "UI/UX Designer",
    company: { name: "Notion", location: "Remote" },
    companyName: "Notion",
    location: "Remote",
    isRemote: true,
    jobType: "Full-time",
    type: "Full-time",
    salary: "₹12L – ₹22L / yr",
    salaryDisplay: "₹12L – ₹22L / yr",
    salaryMin: 1200000,
    salaryMax: 2200000,
    salaryCurrency: "INR",
    posted: "4h ago",
    postedAt: new Date(Date.now() - 4 * 3600000).toISOString(),
    logo: "NT",
    logoColor: "#fff",
    logoBg: "#191919",
    tags: ["Figma", "Prototyping", "User Research"],
    requirements: ["Figma", "Prototyping", "User Research"],
    skills: ["Figma", "Prototyping", "User Research"],
    description: "Design modular, intuitive workspace interfaces that empower people and teams to organize their thoughts, projects, and collaborative knowledge bases.",
    featured: false,
    isExternal: false,
    isDemo: true,
    provider: "demo",
    source: "demo",
  },
  {
    _id: "demo_8",
    id: "demo_8",
    category: "Design",
    title: "Brand Designer",
    company: { name: "Spotify", location: "New York, NY" },
    companyName: "Spotify",
    location: "New York, NY",
    isRemote: false,
    jobType: "Full-time",
    type: "Full-time",
    salary: "₹10L – ₹18L / yr",
    salaryDisplay: "₹10L – ₹18L / yr",
    salaryMin: 1000000,
    salaryMax: 1800000,
    salaryCurrency: "INR",
    posted: "1d ago",
    postedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    logo: "SP",
    logoColor: "#fff",
    logoBg: "#1DB954",
    tags: ["Illustrator", "Brand Identity", "Motion"],
    requirements: ["Illustrator", "Brand Identity", "Motion"],
    skills: ["Illustrator", "Brand Identity", "Motion"],
    description: "Help shape the global visual identity of audio streaming, cultural campaigns, creator spotlights, and dynamic brand expression across mediums.",
    featured: false,
    isExternal: false,
    isDemo: true,
    provider: "demo",
    source: "demo",
  },
  {
    _id: "demo_9",
    id: "demo_9",
    category: "Design",
    title: "Motion Designer",
    company: { name: "Airbnb", location: "San Francisco, CA" },
    companyName: "Airbnb",
    location: "San Francisco, CA",
    isRemote: false,
    jobType: "Hybrid",
    type: "Hybrid",
    salary: "₹14L – ₹24L / yr",
    salaryDisplay: "₹14L – ₹24L / yr",
    salaryMin: 1400000,
    salaryMax: 2400000,
    salaryCurrency: "INR",
    posted: "2d ago",
    postedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    logo: "AB",
    logoColor: "#fff",
    logoBg: "#FF5A5F",
    tags: ["After Effects", "Lottie", "Framer"],
    requirements: ["After Effects", "Lottie", "Framer"],
    skills: ["After Effects", "Lottie", "Framer"],
    description: "Create delightful motion language, micro-interactions, and narrative animations that bring the Airbnb guest and host journey to life.",
    featured: false,
    isExternal: false,
    isDemo: true,
    provider: "demo",
    source: "demo",
  },
  {
    _id: "demo_10",
    id: "demo_10",
    category: "Design",
    title: "Design Systems Lead",
    company: { name: "Shopify", location: "Remote" },
    companyName: "Shopify",
    location: "Remote",
    isRemote: true,
    jobType: "Full-time",
    type: "Full-time",
    salary: "₹25L – ₹40L / yr",
    salaryDisplay: "₹25L – ₹40L / yr",
    salaryMin: 2500000,
    salaryMax: 4000000,
    salaryCurrency: "INR",
    posted: "3d ago",
    postedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    logo: "SH",
    logoColor: "#fff",
    logoBg: "#5a8a00",
    tags: ["Figma", "React", "Storybook"],
    requirements: ["Figma", "React", "Storybook"],
    skills: ["Figma", "React", "Storybook"],
    description: "Lead the evolution of Polaris, Shopify's design system. Establish accessible UI standards, cross-platform component libraries, and seamless design tokens.",
    featured: false,
    isExternal: false,
    isDemo: true,
    provider: "demo",
    source: "demo",
  },
  {
    _id: "demo_22",
    id: "demo_22",
    category: "Design",
    title: "Visual Designer",
    company: { name: "Figma", location: "San Francisco, CA" },
    companyName: "Figma",
    location: "San Francisco, CA",
    isRemote: false,
    jobType: "Full-time",
    type: "Full-time",
    salary: "₹12L – ₹20L / yr",
    salaryDisplay: "₹12L – ₹20L / yr",
    salaryMin: 1200000,
    salaryMax: 2000000,
    salaryCurrency: "INR",
    posted: "6h ago",
    postedAt: new Date(Date.now() - 6 * 3600000).toISOString(),
    logo: "FG",
    logoColor: "#fff",
    logoBg: "#a259ff",
    tags: ["Figma", "Illustration", "Brand"],
    requirements: ["Figma", "Illustration", "Brand"],
    skills: ["Figma", "Illustration", "Brand"],
    description: "Design inspiring marketing collateral, product announcements, and digital experiences that celebrate creativity for the Figma design community.",
    featured: false,
    isExternal: false,
    isDemo: true,
    provider: "demo",
    source: "demo",
  },
  // Finance
  {
    _id: "demo_3",
    id: "demo_3",
    category: "Finance",
    title: "Data Scientist",
    company: { name: "Stripe", location: "New York, NY" },
    companyName: "Stripe",
    location: "New York, NY",
    isRemote: false,
    jobType: "Hybrid",
    type: "Hybrid",
    salary: "₹20L – ₹35L / yr",
    salaryDisplay: "₹20L – ₹35L / yr",
    salaryMin: 2000000,
    salaryMax: 3500000,
    salaryCurrency: "INR",
    posted: "1d ago",
    postedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    logo: "ST",
    logoColor: "#fff",
    logoBg: "#635bff",
    tags: ["Python", "Machine Learning", "SQL"],
    requirements: ["Python", "Machine Learning", "SQL"],
    skills: ["Python", "Machine Learning", "SQL"],
    description: "Build state-of-the-art fraud detection algorithms, global transaction forecasting models, and quantitative financial risk intelligence systems.",
    featured: false,
    isExternal: false,
    isDemo: true,
    provider: "demo",
    source: "demo",
  },
  {
    _id: "demo_11",
    id: "demo_11",
    category: "Finance",
    title: "Financial Analyst",
    company: { name: "Coinbase", location: "Remote" },
    companyName: "Coinbase",
    location: "Remote",
    isRemote: true,
    jobType: "Full-time",
    type: "Full-time",
    salary: "₹12L – ₹22L / yr",
    salaryDisplay: "₹12L – ₹22L / yr",
    salaryMin: 1200000,
    salaryMax: 2200000,
    salaryCurrency: "INR",
    posted: "1d ago",
    postedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    logo: "CB",
    logoColor: "#fff",
    logoBg: "#0052FF",
    tags: ["Excel", "SQL", "Financial Modeling"],
    requirements: ["Excel", "SQL", "Financial Modeling"],
    skills: ["Excel", "SQL", "Financial Modeling"],
    description: "Analyze crypto market liquidity, capital allocation models, corporate treasuries, and real-time revenue performance for global trading operations.",
    featured: false,
    isExternal: false,
    isDemo: true,
    provider: "demo",
    source: "demo",
  },
  {
    _id: "demo_12",
    id: "demo_12",
    category: "Finance",
    title: "Risk Manager",
    company: { name: "Robinhood", location: "Menlo Park, CA" },
    companyName: "Robinhood",
    location: "Menlo Park, CA",
    isRemote: false,
    jobType: "Hybrid",
    type: "Hybrid",
    salary: "₹18L – ₹30L / yr",
    salaryDisplay: "₹18L – ₹30L / yr",
    salaryMin: 1800000,
    salaryMax: 3000000,
    salaryCurrency: "INR",
    posted: "4d ago",
    postedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    logo: "RH",
    logoColor: "#fff",
    logoBg: "#00C805",
    tags: ["Risk Analysis", "Python", "Bloomberg"],
    requirements: ["Risk Analysis", "Python", "Bloomberg"],
    skills: ["Risk Analysis", "Python", "Bloomberg"],
    description: "Oversee algorithmic trading compliance, regulatory stress testing, counterparty exposure mitigation, and real-time market risk metrics.",
    featured: false,
    isExternal: false,
    isDemo: true,
    provider: "demo",
    source: "demo",
  },
  // Marketing
  {
    _id: "demo_6",
    id: "demo_6",
    category: "Marketing",
    title: "Growth Marketing Lead",
    company: { name: "Figma", location: "Austin, TX" },
    companyName: "Figma",
    location: "Austin, TX",
    isRemote: false,
    jobType: "Hybrid",
    type: "Hybrid",
    salary: "₹18L – ₹28L / yr",
    salaryDisplay: "₹18L – ₹28L / yr",
    salaryMin: 1800000,
    salaryMax: 2800000,
    salaryCurrency: "INR",
    posted: "3d ago",
    postedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    logo: "FG",
    logoColor: "#fff",
    logoBg: "#a259ff",
    tags: ["SEO", "Analytics", "Paid Ads"],
    requirements: ["SEO", "Analytics", "Paid Ads"],
    skills: ["SEO", "Analytics", "Paid Ads"],
    description: "Scale organic acquisition loops, enterprise inbound funnels, and data-driven user conversion strategies across North American and European markets.",
    featured: false,
    isExternal: false,
    isDemo: true,
    provider: "demo",
    source: "demo",
  },
  {
    _id: "demo_13",
    id: "demo_13",
    category: "Marketing",
    title: "Content Strategist",
    company: { name: "HubSpot", location: "Remote" },
    companyName: "HubSpot",
    location: "Remote",
    isRemote: true,
    jobType: "Full-time",
    type: "Full-time",
    salary: "₹8L – ₹15L / yr",
    salaryDisplay: "₹8L – ₹15L / yr",
    salaryMin: 800000,
    salaryMax: 1500000,
    salaryCurrency: "INR",
    posted: "2d ago",
    postedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    logo: "HS",
    logoColor: "#fff",
    logoBg: "#FF7A59",
    tags: ["Content", "SEO", "HubSpot CMS"],
    requirements: ["Content", "SEO", "HubSpot CMS"],
    skills: ["Content", "SEO", "HubSpot CMS"],
    description: "Architect thought-leadership publications, high-converting product narratives, and educational resources that empower modern sales and marketing teams.",
    featured: false,
    isExternal: false,
    isDemo: true,
    provider: "demo",
    source: "demo",
  },
  {
    _id: "demo_23",
    id: "demo_23",
    category: "Marketing",
    title: "Performance Marketing Manager",
    company: { name: "Notion", location: "Remote" },
    companyName: "Notion",
    location: "Remote",
    isRemote: true,
    jobType: "Full-time",
    type: "Full-time",
    salary: "₹12L – ₹20L / yr",
    salaryDisplay: "₹12L – ₹20L / yr",
    salaryMin: 1200000,
    salaryMax: 2000000,
    salaryCurrency: "INR",
    posted: "5d ago",
    postedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    logo: "NT",
    logoColor: "#fff",
    logoBg: "#191919",
    tags: ["Google Ads", "Meta", "A/B Testing"],
    requirements: ["Google Ads", "Meta", "A/B Testing"],
    skills: ["Google Ads", "Meta", "A/B Testing"],
    description: "Lead multi-channel performance advertising, creative experimentation, customer acquisition optimization, and CAC-to-LTV attribution modeling.",
    featured: false,
    isExternal: false,
    isDemo: true,
    provider: "demo",
    source: "demo",
  },
  // Healthcare
  {
    _id: "demo_14",
    id: "demo_14",
    category: "Healthcare",
    title: "Health Data Analyst",
    company: { name: "Epic", location: "Madison, WI" },
    companyName: "Epic",
    location: "Madison, WI",
    isRemote: false,
    jobType: "Full-time",
    type: "Full-time",
    salary: "₹10L – ₹18L / yr",
    salaryDisplay: "₹10L – ₹18L / yr",
    salaryMin: 1000000,
    salaryMax: 1800000,
    salaryCurrency: "INR",
    posted: "1d ago",
    postedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    logo: "EP",
    logoColor: "#fff",
    logoBg: "#c0392b",
    tags: ["HL7", "SQL", "Tableau"],
    requirements: ["HL7", "SQL", "Tableau"],
    skills: ["HL7", "SQL", "Tableau"],
    description: "Analyze clinical trial outcomes, hospital operational metrics, and EHR records to improve patient care protocols across major hospital networks.",
    featured: false,
    isExternal: false,
    isDemo: true,
    provider: "demo",
    source: "demo",
  },
  {
    _id: "demo_15",
    id: "demo_15",
    category: "Healthcare",
    title: "Clinical Software Engineer",
    company: { name: "Nuna", location: "Remote" },
    companyName: "Nuna",
    location: "Remote",
    isRemote: true,
    jobType: "Full-time",
    type: "Full-time",
    salary: "₹16L – ₹28L / yr",
    salaryDisplay: "₹16L – ₹28L / yr",
    salaryMin: 1600000,
    salaryMax: 2800000,
    salaryCurrency: "INR",
    posted: "3d ago",
    postedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    logo: "NU",
    logoColor: "#fff",
    logoBg: "#2980b9",
    tags: ["Python", "FHIR", "REST API"],
    requirements: ["Python", "FHIR", "REST API"],
    skills: ["Python", "FHIR", "REST API"],
    description: "Develop secure healthcare interoperability platforms, value-based care analytics engines, and compliant patient health data pipelines.",
    featured: false,
    isExternal: false,
    isDemo: true,
    provider: "demo",
    source: "demo",
  },
  // Security
  {
    _id: "demo_16",
    id: "demo_16",
    category: "Security",
    title: "Security Engineer",
    company: { name: "Cloudflare", location: "Remote" },
    companyName: "Cloudflare",
    location: "Remote",
    isRemote: true,
    jobType: "Full-time",
    type: "Full-time",
    salary: "₹22L – ₹38L / yr",
    salaryDisplay: "₹22L – ₹38L / yr",
    salaryMin: 2200000,
    salaryMax: 3800000,
    salaryCurrency: "INR",
    posted: "2d ago",
    postedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    logo: "CF",
    logoColor: "#fff",
    logoBg: "#F6821F",
    tags: ["Cybersecurity", "Rust", "Zero Trust"],
    requirements: ["Cybersecurity", "Rust", "Zero Trust"],
    skills: ["Cybersecurity", "Rust", "Zero Trust"],
    description: "Fortify edge routing networks, build automated DDoS mitigation tools, and deploy Zero Trust architecture protecting millions of websites.",
    featured: false,
    isExternal: false,
    isDemo: true,
    provider: "demo",
    source: "demo",
  },
  {
    _id: "demo_17",
    id: "demo_17",
    category: "Security",
    title: "Penetration Tester",
    company: { name: "HackerOne", location: "Remote" },
    companyName: "HackerOne",
    location: "Remote",
    isRemote: true,
    jobType: "Contract",
    type: "Contract",
    salary: "₹15L – ₹26L / yr",
    salaryDisplay: "₹15L – ₹26L / yr",
    salaryMin: 1500000,
    salaryMax: 2600000,
    salaryCurrency: "INR",
    posted: "5d ago",
    postedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    logo: "H1",
    logoColor: "#fff",
    logoBg: "#494368",
    tags: ["Bug Bounty", "Cybersecurity", "Linux"],
    requirements: ["Bug Bounty", "Cybersecurity", "Linux"],
    skills: ["Bug Bounty", "Cybersecurity", "Linux"],
    description: "Conduct comprehensive penetration tests, red-team simulations, and vulnerability disclosures across enterprise cloud systems.",
    featured: false,
    isExternal: false,
    isDemo: true,
    provider: "demo",
    source: "demo",
  },
  // Education
  {
    _id: "demo_18",
    id: "demo_18",
    category: "Education",
    title: "EdTech Product Manager",
    company: { name: "Coursera", location: "Remote" },
    companyName: "Coursera",
    location: "Remote",
    isRemote: true,
    jobType: "Full-time",
    type: "Full-time",
    salary: "₹18L – ₹32L / yr",
    salaryDisplay: "₹18L – ₹32L / yr",
    salaryMin: 1800000,
    salaryMax: 3200000,
    salaryCurrency: "INR",
    posted: "6d ago",
    postedAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    logo: "CO",
    logoColor: "#fff",
    logoBg: "#0056D2",
    tags: ["Product", "EdTech", "Analytics"],
    requirements: ["Product", "EdTech", "Analytics"],
    skills: ["Product", "EdTech", "Analytics"],
    description: "Lead university degree platform features, asynchronous classroom tooling, and student learning outcome analytics for millions of learners.",
    featured: false,
    isExternal: false,
    isDemo: true,
    provider: "demo",
    source: "demo",
  },
  {
    _id: "demo_24",
    id: "demo_24",
    category: "Education",
    title: "Curriculum Designer",
    company: { name: "Khan Academy", location: "Remote" },
    companyName: "Khan Academy",
    location: "Remote",
    isRemote: true,
    jobType: "Full-time",
    type: "Full-time",
    salary: "₹8L – ₹15L / yr",
    salaryDisplay: "₹8L – ₹15L / yr",
    salaryMin: 800000,
    salaryMax: 1500000,
    salaryCurrency: "INR",
    posted: "4d ago",
    postedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    logo: "KA",
    logoColor: "#fff",
    logoBg: "#14BF96",
    tags: ["Instructional Design", "SCORM", "LMS"],
    requirements: ["Instructional Design", "SCORM", "LMS"],
    skills: ["Instructional Design", "SCORM", "LMS"],
    description: "Design interactive, mastery-based learning modules in STEM, computer science, and mathematics for learners around the world.",
    featured: false,
    isExternal: false,
    isDemo: true,
    provider: "demo",
    source: "demo",
  },
  // Engineering Ops
  {
    _id: "demo_19",
    id: "demo_19",
    category: "Engineering Ops",
    title: "Site Reliability Engineer",
    company: { name: "Netflix", location: "Remote" },
    companyName: "Netflix",
    location: "Remote",
    isRemote: true,
    jobType: "Full-time",
    type: "Full-time",
    salary: "₹28L – ₹45L / yr",
    salaryDisplay: "₹28L – ₹45L / yr",
    salaryMin: 2800000,
    salaryMax: 4500000,
    salaryCurrency: "INR",
    posted: "1d ago",
    postedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    logo: "NF",
    logoColor: "#fff",
    logoBg: "#E50914",
    tags: ["AWS", "Python", "Linux"],
    requirements: ["AWS", "Python", "Linux"],
    skills: ["AWS", "Python", "Linux"],
    description: "Design chaos engineering experiments, automated failover systems, and ultra-high reliability streaming infrastructure serving global traffic spikes.",
    featured: false,
    isExternal: false,
    isDemo: true,
    provider: "demo",
    source: "demo",
  },
  {
    _id: "demo_20",
    id: "demo_20",
    category: "Engineering Ops",
    title: "Platform Engineer",
    company: { name: "Datadog", location: "New York, NY" },
    companyName: "Datadog",
    location: "New York, NY",
    isRemote: false,
    jobType: "Hybrid",
    type: "Hybrid",
    salary: "₹24L – ₹38L / yr",
    salaryDisplay: "₹24L – ₹38L / yr",
    salaryMin: 2400000,
    salaryMax: 3800000,
    salaryCurrency: "INR",
    posted: "4d ago",
    postedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    logo: "DD",
    logoColor: "#fff",
    logoBg: "#632CA6",
    tags: ["Kubernetes", "Terraform", "Go"],
    requirements: ["Kubernetes", "Terraform", "Go"],
    skills: ["Kubernetes", "Terraform", "Go"],
    description: "Build internal developer platforms, container orchestration engines, and telemetry monitoring pipelines that support hundreds of microservices.",
    featured: false,
    isExternal: false,
    isDemo: true,
    provider: "demo",
    source: "demo",
  },
];
